routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SiteController@index')->name('main');
Route::get('about','SiteController@about')->name('about');
Route::get('contact','SiteController@contact')->name('contact');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courses', 'Website\CourseController');
Route::resource('posts', 'Website\PostController');
Route::get('courses_enroll/{course_id}','Website\CourseController@enroll')->name('course.enroll');

Route::group(['prefix' => 'dashboard','as'=>'dashboard.','middleware'=>'admin','namespace'=>'Dashboard'], function () {

Route::get('/', 'MainController@index')->name('home');
// user routes controllers
Route::resource('users', 'UserController');
Route::get('delete_user/{id}','UserController@destroy')->name('users.user_destroy');

// category routes controllers
Route::resource('categories', 'CategoryController');
Route::get('delete_category/{id}','CategoryController@destroy')->name('categories.category_destroy');

// courses routes controllers
Route::resource('courses', 'CourseController');
Route::get('delete_course/{id}','CourseController@destroy')->name('courses.course_destroy');

// lessons routes controllers
Route::resource('lessons', 'LessonController');
Route::get('delete_lesson/{id}','LessonController@destroy')->name('lessons.lesson_destroy');

// messages routes controllers
Route::resource('message', 'ContactController');
Route::get('delete_message/{id}','ContactController@destroy')->name('message.message_destroy');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_active', 'role', 'phone', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $categories = Category::orderBy('id', 'desc')->get();
          return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'required|file|max:2048|mimes:png,jpeg,jpg',
        ]);

        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Category::create($inputes);
        return redirect(route('dashboard.categories.index'))->with('success', 'You Have Added New Category Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);
        return view('dashboard.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'required|file|max:2048',
        ]);
        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Category::find($id)->update($inputes);
        return redirect(route('dashboard.categories.index'))->with('success', 'You Have Updated This Category Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if(!$category)  return back()->with('error','Category Does Not Exist!');
        $category->delete();
        return redirect(route('dashboard.categories.index'))->with('success', 'Category Deleted Successfully.');
    }
}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Contact;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $messages = Contact::all();
        return view('dashboard.messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'email'=>'required|email|max:191|unique:users,email',
            'phone'=>'required|string|max:191|unique:users,phone',
            'message'=>'required',
        ]);

        // if(!auth()->user()) return back()->with('error', 'You Are Not Registered In Our Website!');
       Contact::create($request->all());
       return redirect(route('contact'))->with('success', 'Your Message Sent Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $message = Contact::findOrFail($id);
        return view('dashboard.messages.show', compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = Contact::find($id);
        if(!$message) return back()->with('error', 'Message Does not Exist!');
        $message->delete();
        return redirect(route('dashboard.messages.index'))->with('success', 'Message Deleted Successfully.');
    }
}

app/Http/Controllers/Dashboard/CourseController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Course;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courses = Course::all();
        return view('dashboard.courses.index', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.courses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'rquired|file|max:2048|mimes:png,jpeg,jpg',
            'short_description'=>'required',
            'long_description'=>'required',
            'price'=>'required|decimal',
            'category_id'=>'required|string|max:191',
        ]);
        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Course::create($inputes);
        return redirect(route('dashboard.courses.index'))->with('success', 'You Have Added New Course Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $course = Course::findOrFail($id);
        return view('dashboard.courses.show', compact('course'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $course = Course::findOrFail($id);
        return view('dashboard.courses.edit', compact('course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $course = Course::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'rquired|file|max:2048|mimes:png,jpeg,jpg',
            'short_description'=>'required',
            'long_description'=>'sometimes',
            'price'=>'required|decimal',
            'category_id'=>'required|string|max:191',
        ]);
        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Course::find($id)->update($inputes);
        return redirect(route('dashboard.courses.index'))->with('success', 'You Have Updated This Course Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $course = Course::find($id);
        if(!$course) return back()->with('error', 'Course Does not Exist!');
        $course->delete();
        return redirect(route('dashboard.courses.index'))->with('success', 'Course Deleted Successfully.');

    }
}

app/Http/Controllers/Dashboard/LessonController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Lesson;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lessons = Lesson::orderBy('course_id', 'asc')->get();
        return view('dashboard.lessons.index', compact('lessons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.lessons.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'url'=>'required|url|unique:lessons,url',
            'duration'=>'required|date',
            'course_id'=>'required|string|max:191',
        ]);

        $inputes = $request->all();
        Lesson::create($inputes);
        return redirect(route('dashboard.lessons.index'))->with('success', 'You Have Added New Lesson Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $lesson = Lesson::findOrFail($id);
        return view('dashboard.lessons.show', compact('lesson'));

        }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lesson = Lesson::findOrFail($id);
        return view('dashboard.lessons.edit', compact('lesson'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'url'=>'required|url|unique:lessons,url',
            'duration'=>'required|date',
            'course_id'=>'required|string|max:191',
        ]);

        $inputes = $request->all();
        Lesson::find($id)->update($inputes);
        return redirect(route('dashboard.lessons.index'))->with('success', 'You Have Updated This Lesson Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lesson = Lesson::find($id);
        if(!$lesson) return back()->with('error', 'Lesson Does not Exist!');
        $lesson->delete();
        return redirect(route('dashboard.lessons.index'))->with('success', 'Lesson Deleted Successfully.');
    }
}

app/Http/Controllers/Dashboard/MainController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index()
    {
        return view('Dashboard.main');
    }
}

resources/views/Dashboard/Users/create.blade.php
@extends('Dashboard.Layouts.layout')

@section('title')
    Add New User
@endsection

@section('content')
<!-- Input group addons -->
<div class="panel panel-flat">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

{!! Form::open(['route'=>'dashboard.users.store','method'=>'POST','files'=>true]) !!}

@include('Dashboard.Layouts.form')

{!! Form::close() !!}
</div>
<!-- /input group addons -->

@endsection

resources/views/Dashboard/Users/edit.blade.php
@extends('Dashboard.Layouts.layout')

@section('title')
    Editing {{$user->name}}
@endsection

@section('content')
<!-- Input group addons -->
<div class="panel panel-flat">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
{!! Form::model($user, ['route'=>['dashboard.users.update', $user->id], 'method'=>'PATCH', 'files'=>true] ) !!}
@csrf
@include('Dashboard.Layouts.form')

{!! Form::close() !!}
</div>
<!-- /input group addons -->
@endsection

resources/views/Dashboard/Users/index.blade.php
@extends('Dashboard.Layouts.layout')

@section('title')
    All Users
@endsection

@section('content')

<div class="panel panel-flat">
    <div class="panel-heading">
        <p class="panel-title">You Can Show All Users And performs All operations like search , Edit , show And Delete.</p>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table datatable-button-init-basic">
            <thead>
                <tr class="bg-blue">
                    <th>No#</th>
                    <th>First Name</th>
                    <th>E-mail</th>
                    <th>Phone</th>
                    <th>Image</th>
                    <th>Active Status</th>
                    <th>Role</th>
                </tr>
            </thead>
            <tbody>
                <?php $no=1; ?>
                @foreach ($users as $user)
                <tr>
                    <td>{{$no++}}</td>
                    <td><a href="{{route('dashboard.users.show', $user->id)}}">{{$user->name}}</a></td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->phone}}</td>
                    <td><img src="{{getimage($user->image)}}" alt="" style="width: 80px; height: 80px"></td>
                <td>{{statusArray()[$user->is_active]}}</td>
                    <td>{{$user->role}}</td>
                </tr>
                @endforeach

            </tbody>
        </table>
    </div>
</div>
<br><br>
<!-- /table header styling -->

@endsection

resources/views/Dashboard/Users/show.blade.php
@extends('Dashboard.Layouts.layout')

@section('title')
    User Settings
@endsection

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Editing One User</h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr class="bg-blue">
                    <th>#</th>
                    <th>First Name</th>
                    <th>E-mail</th>
                    <th>Phone</th>
                    <th>Image</th>
                    <th>Role</th>
                    <th>Control</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{$user->id}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->phone}}</td>
                    <td><img src="{{asset('website/img/'.$user->image)}}" alt="" style="width: 80px; height: 80px"></td>
                    <td>{{$user->role}}</td>
                    <td>
                    <a href="{{route('dashboard.users.edit', $user->id)}}" class="btn btn-info"><i class="fa fa-user-edit">&nbsp;</i>Edit User</a></<a><span>&nbsp;</span>
                    <a href="{{route('dashboard.users.user_destroy', $user->id)}}" class="btn btn-danger"><i class="fa fa-user-minus">&nbsp;</i>Delete User</a></<a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<!-- /table header styling -->

@endsection