routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SiteController@index')->name('main');
Route::get('about','SiteController@about')->name('about');
Route::get('contact','SiteController@contact')->name('contact');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courses', 'Website\CourseController');
Route::resource('posts', 'Website\PostController');
Route::get('courses_enroll/{course_id}','Website\CourseController@enroll')->name('course.enroll');

Route::group(['prefix' => 'dashboard','as'=>'dashboard.','middleware'=>'admin','namespace'=>'Dashboard'], function () {

Route::get('/', 'MainController@index')->name('home');
// user routes controllers
Route::resource('users', 'UserController');
Route::get('delete_user/{id}','UserController@destroy')->name('users.user_destroy');

// category routes controllers
Route::resource('categories', 'CategoryController');
Route::get('delete_category/{id}','CategoryController@destroy')->name('categories.category_destroy');

// courses routes controllers
Route::resource('courses', 'CourseController');
Route::get('delete_course/{id}','CourseController@destroy')->name('courses.course_destroy');

// lessons routes controllers
Route::resource('lessons', 'LessonController');
Route::get('delete_lesson/{id}','LessonController@destroy')->name('lessons.lesson_destroy');

// messages routes controllers
Route::resource('message', 'ContactController');
Route::get('delete_message/{id}','ContactController@destroy')->name('message.message_destroy');

});

app/Http/Controllers/Website/CourseController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Course;
use App\Category;
use App\Review;
use App\CourseEnroll;

class CourseController extends Controller
{
    public function index()
    {
        $courses = Course::orderby('id','desc')->get();
        $categories = Category::all();
        return view('Website.Courses.index')
        ->with('courses', $courses)->with('categories', $categories);

    }

    public function show($id)
    {
        $course = Course::findOrFail($id);

        return view('Website.Courses.show')
        ->with('course', $course);
    }

    public function enroll($course_id)
    {
        if(!auth()->check()) return redirect(route('login'));
        $course = Course::findOrFail($course_id);
        $course_enrolled = Course::Enrolled()->first();
        if ($course_enrolled) return back();

        CourseEnroll::create([
            'course_id'=>$course_id,
            'user_id'=>auth()->user()->id,
            'is_confirmed'=>0
        ]);

      return back();

    }

}

app/Http/Controllers/Website/PostController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Post;

class PostController extends Controller
{
    public function index()
    {
        $posts  = Post::Orderby('id','desc')->get();
        return view('Website.Posts.index')
        ->with('posts',$posts);
    }

    public function show($id)
    {
        $post = Post::findOrFail($id);

        return view('Website.Posts.show')
        ->with('post', $post);
    }
}

resources/views/website/about.blade.php
@extends('website\layout')


@section('content')

<section id="hero_in" class="general">
    <div class="wrapper">
        <div class="container">
            <h1 class="fadeInUp"><span></span>About Udema</h1>
        </div>
    </div>
</section>
<!--/hero_in-->

<div class="container margin_120_95">
    <div class="main_title_2">
        <span><em></em></span>
        <h2>Why choose Udema</h2>
        <p>When they become educated citizens in the financing deterred.</p>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <a class="box_feat" href="#">
                <i class="pe-7s-diamond"></i>
                <h3>Qualified teachers</h3>
                <p>Which, in my congue dictum, not even with the most admirable mazim.Unusual not allow it. I hear you interpret the attacks with no other option, since the books mazim.Unusual.</p>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a class="box_feat" href="#">
                <i class="pe-7s-display2"></i>
                <h3>Equiped class rooms</h3>
                <p>Which, in my congue dictum, not even with the most admirable mazim.Unusual not allow it. I hear you interpret the attacks with no other option, since the books mazim.Unusual. </p>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a class="box_feat" href="#">
                <i class="pe-7s-science"></i>
                <h3>Advanced teaching</h3>
                <p>Which, in my congue dictum, not even with the most admirable mazim.Unusual not allow it. I hear you interpret the attacks with no other option, since the books mazim.Unusual.</p>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a class="box_feat" href="#">
                <i class="pe-7s-rocket"></i>
                <h3>Adavanced study plans</h3>
                <p>Which, in my congue dictum, not even with the most admirable mazim.Unusual not allow it. I hear you interpret the attacks with no other option, since the books mazim.Unusual. </p>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a class="box_feat" href="#">
                <i class="pe-7s-target"></i>
                <h3>Focus on target</h3>
                <p>Which, in my congue dictum, not even with the most admirable mazim.Unusual not allow it. I hear you interpret the attacks with no other option, since the books mazim.Unusual.</p>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a class="box_feat" href="#">
                <i class="pe-7s-graph1"></i>
                <h3>focus on success</h3>
                <p>Which, in my congue dictum, not even with the most admirable mazim.Unusual not allow it. I hear you interpret the attacks with no other option, since the books mazim.Unusual. </p>
            </a>
        </div>
    </div>
    <!--/row-->
</div>
<!-- /container -->
{{-- ===============================*=========================== --}}
<div class="bg_color_1">
    <div class="container margin_120_95">
        <div class="main_title_2">
            <span><em></em></span>
            <h2>Our Origins and Story</h2>
            <p>When they become educated citizens in the financing deterred.</p>
        </div>
        <div class="row justify-content-between">
            <div class="col-lg-6 wow" data-wow-offset="150">
                <figure class="block-reveal">
                    <div class="block-horizzontal"></div>
                    <img src="{{asset('website/img/edu.jpg')}}" class="img-fluid" alt="">
                </figure>
            </div>
            <div class="col-lg-5">
                <p>Lorem ipsum dolor sit amet, homero erroribus in cum. Cu eos <strong>scaevola probatus</strong>. Nam atqui intellegat ei, sed ex graece essent delectus. Autem consul eum ea. Duo cu fabulas nonumes contentiones, nihil voluptaria pro id. Has graeci deterruisset ad, est no primis detracto pertinax, at cum malis vitae facilisis.</p>
                <p>Dicam diceret ut ius, no epicuri dissentiet philosophia vix. Id usu zril tacimates neglegentur. Eam id legimus torquatos cotidieque, usu decore <strong>percipitur definitiones</strong> ex, nihil utinam recusabo mel no. Dolores reprehendunt no sit, quo cu viris theophrastus. Sit unum efficiendi cu.</p>
                <p><em>CEO Marc Schumaker</em></p>
            </div>
        </div>
        <!--/row-->
    </div>
    <!--/container-->
</div>
<!--/bg_color_1-->

<div class="container margin_120_95">
    <div class="main_title_2">
        <span><em></em></span>
        <h2>Our founders</h2>
        <p>When they become educated citizens in the financing deterred.</p>
    </div>
    <div id="carousel" class="owl-carousel owl-theme">
        <div class="item">
            <a href="#0">
                <div class="title">
                    <h4>Joe Smith<em>CEO</em></h4>
                </div><img src="{{asset('website/img/founder1.jpg')}}" alt="" style="width: 270px; height: 385.7px">
            </a>
        </div>
        <div class="item">
            <a href="#0">
                <div class="title">
                    <h4>Lucas Smith<em>Marketing</em></h4>
                </div><img src="{{asset('website/img/founder2.jpg')}}" alt="" style="width: 270px; height: 385.7px">
            </a>
        </div>
        <div class="item">
            <a href="#0">
                <div class="title">
                    <h4>Paul Stephens<em>Business strategist</em></h4>
                </div><img src="{{asset('website/img/founder3.jpg')}}" alt="" style="width: 270px; height: 385.7px">
            </a>
        </div>
        <div class="item">
            <a href="#0">
                <div class="title">
                    <h4>Pablo Himenez<em>Customer Service</em></h4>
                </div><img src="{{asset('website/img/founder4.jpg')}}" alt="" style="width: 270px; height: 385.7px">
            </a>
        </div>
        <div class="item">
            <a href="#0">
                <div class="title">
                    <h4>Andrew Stuttgart<em>Admissions</em></h4>
                </div><img src="{{asset('website/img/founder5.jpg')}}" alt="" style="width: 270px; height: 385.7px">
            </a>
        </div>
    </div>
    <!-- /carousel -->
</div>
<!--/container-->

@endsection

resources/views/website/contact.blade.php
@extends('website\layout')

@section('content')

<section id="hero_in" class="contacts">
    <div class="wrapper">
        <div class="container">
            <h1 class="fadeInUp"><span></span>Contact &nbsp;Us</h1>
        </div>
    </div>
</section>
<!--/hero_in-->

<div class="contact_info">
    <div class="container">
        <ul class="clearfix">
            <li>
                <i class="pe-7s-map-marker"></i>
                <h4>Address</h4>
                <span>PO Box 97845 Baker st. 567, Los Angeles<br>California - US.</span>
            </li>
            <li>
                <i class="pe-7s-mail-open-file"></i>
                <h4>Email address</h4>
                <span>admission@udema.com - info@udema.com<br><small>Monday to Friday 9am - 7pm</small></span>

            </li>
            <li>
                <i class="pe-7s-phone"></i>
                <h4>Contacts info</h4>
                <span>+ 61 (2) 8093 3402 + 61 (2) 8093 3402<br><small>Monday to Friday 9am - 7pm</small></span>
            </li>
        </ul>
    </div>
</div>
<!--/contact_info-->

<div class="bg_color_1">
    <div class="container margin_120_95">
        <div class="row justify-content-between">
            <div class="col-lg-5">
                <div class="map_contact">
                </div>
                <!-- /map -->
            </div>
            <div class="col-lg-6">
                <h4>Send a message</h4>
                <p>Inquiries and technical support and reporting any technical and technical errors on the site.</p>
                <div id="message-contact"></div>
            @if ($errors->any())
                <div class="alert alert-danger">
                <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
               </ul>
               </div>
            @endif
{{-- =================================================== --}}
{!! Form::open(['route'=>['dashboard.message.store'],'method'=>'POST', 'files'=>true]) !!}
                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <span class="input">
                    {!! Form::text('name', null, ['class'=>'input_field','id'=>'name_contact']) !!}
                                <label class="input_label">
                                    <span class="input__label-content">Your Name</span>
                                </label>
                            </span>
                        </div>
                    </div>
                    <!-- /row -->
                    <div class="row">
                        <div class="col-md-6">
                            <span class="input">
                    {!! Form::email('email', null, ['class'=>'input_field', 'id'=>'email_contact']) !!}
                                <label class="input_label">
                                    <span class="input__label-content">Your email</span>
                                </label>
                            </span>
                        </div>
                        <div class="col-md-6">
                            <span class="input">
                    {!! Form::text('phone', null, ['class'=>'input_field', 'id'=>'phone_contact']) !!}
                                <label class="input_label">
                                    <span class="input__label-content">Your telephone</span>
                                </label>
                            </span>
                        </div>
                    </div>
                    <!-- /row -->
                    <span class="input">
                {!! Form::textarea('message', null, ['class'=>'input_field', 'id'=>'message_contact', 'style'=>'hieght:150px;']) !!}
                            <label class="input_label">
                                <span class="input__label-content">Your message</span>
                            </label>
                    </span>
                    <span class="input">
                            <input class="input_field" type="text" id="verify_contact" name="verify">
                            <label class="input_label">
                            <span class="input__label-content">Are you human? 3 + 1 =</span>
                            </label>
                    </span>
                    <p class="add_top_30"><button type="submit" class="btn_1 rounded" id="submit-contact">Send Message</button>
                    </p>

    {!! Form::close() !!}

{{-- =================================================== --}}
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /bg_color_1 -->

@endsection

resources/views/website/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Udema a modern educational site template">
    <meta name="author" content="Ansonika">
    <title>UDEMA | Modern Educational site template - SHARED ON THEMELOCK.COM</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="/website/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="/website/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="/website/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="/website/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="/website/img/apple-touch-icon-144x144-precomposed.png">

    <!-- BASE CSS -->
    <link href="/website/css/bootstrap.min.css" rel="stylesheet">
    <link href="/website/css/style.css" rel="stylesheet">
	<link href="/website/css/vendors.css" rel="stylesheet">
	<link href="/website/css/icon_fonts/css/all_icons.min.css" rel="stylesheet">

	@yield('styles')

    <!-- YOUR CUSTOM CSS -->
    <link href="/website/css/custom.css" rel="stylesheet">

</head>

<body>

	<div id="page">

	<header class="header menu_2">
		<div id="preloader"><div data-loader="circle-side"></div></div><!-- /Preload -->
		<div id="logo">
			<a href="/"><img src="/website/img/logo.png" width="149" height="42" data-retina="true" alt=""></a>
		</div>
		<ul id="top_menu">
		@if(!auth()->check())
			<li><a href="{{route('login')}}" class="login">Login</a></li>
			@else
			<li><a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
									</li>

									<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">


								   <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
									   @csrf
								   </form>
							   </div>
			@endif
			<li><a href="#0" class="search-overlay-menu-btn">Search</a></li>
			<li class="hidden_tablet"><a href="{{route('dashboard.home')}}" class="btn_1 rounded">Admission</a></li>
		</ul>
		<!-- /top_menu -->
		<a href="#menu" class="btn_mobile">
			<div class="hamburger hamburger--spin" id="hamburger">
				<div class="hamburger-box">
					<div class="hamburger-inner"></div>
				</div>
			</div>
		</a>

@include('Website.nav')

		<!-- Search Menu -->
		<div class="search-overlay-menu">
			<span class="search-overlay-close"><span class="closebt"><i class="ti-close"></i></span></span>
			<form role="search" id="searchform" method="get">
				<input value="" name="q" type="search" placeholder="Search..." />
				<button type="submit"><i class="icon_search"></i>
				</button>
			</form>
		</div><!-- End Search Menu -->
	</header>
	<!-- /header -->

	<main>
@yield('content')
	</main>
	<!-- /main -->

	<footer>
		<div class="container margin_120_95">
			<div class="row">
				<div class="col-lg-5 col-md-12 p-r-5">
					<p><img src="/website/img/logo.png" width="149" height="42" data-retina="true" alt=""></p>
					<p>Mea nibh meis philosophia eu. Duis legimus efficiantur ea sea. Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu. Nihil facilisi indoctum an vix, ut delectus expetendis vis.</p>
					<div class="follow_us">
						<ul>
							<li>Follow us</li>
							<li><a href="https//www.fb.com/udema"><i class="ti-facebook"></i></a></li>
							<li><a href="https//www.twitter.com/udema"><i class="ti-twitter-alt"></i></a></li>
							<li><a href="https//www.google.com/udema"><i class="ti-google"></i></a></li>
							<li><a href="https//www.pinterest.com/udema"><i class="ti-pinterest"></i></a></li>
							<li><a href="https//www.instagram.com/udema"><i class="ti-instagram"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 ml-lg-auto">
					<h5>Useful links</h5>
					<ul class="links">
						<li><a href="{{route('dashboard.home')}}">Admission</a></li>
						<li><a href="{{route('about')}}">About</a></li>
                    <li><a href="{{route('login')}}">Login</a></li>
						<li><a href="{{route('register')}}">Register</a></li>
						<li><a href="{{route('posts.index')}}">News &amp; Events</a></li>
						<li><a href="{{route('contact')}}">Contacts</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-6">
					<h5>Contact with Us</h5>
					<ul class="contacts">
						<li><a href="tel://61280932400"><i class="ti-mobile"></i> + 61 23 8093 3400</a></li>
						<li><a href="mailto:info@udema.com"><i class="ti-email"></i> info@udema.com</a></li>
					</ul>
					<div id="newsletter">
					<h6>Newsletter</h6>
					<div id="message-newsletter"></div>
					<form method="post" action="assets/newsletter.php" name="newsletter_form" id="newsletter_form">
						<div class="form-group">
							<input type="email" name="email_newsletter" id="email_newsletter" class="form-control" placeholder="Your email">
							<input type="submit" value="Submit" id="submit-newsletter">
						</div>
					</form>
					</div>
				</div>
			</div>
			<!--/row-->
			<hr>
			<div class="row">
				<div class="col-md-8">
					<ul id="additional_links">
						<li><a href="#0">Terms and conditions</a></li>
						<li><a href="#0">Privacy</a></li>
					</ul>
				</div>
				<div class="col-md-4">
					<div id="copy">© 2020 Udema</div>
				</div>
			</div>
		</div>
	</footer>
	<!--/footer-->
	</div>
	<!-- page -->

	<!-- COMMON SCRIPTS -->
    <script src="/website/js/jquery-2.2.4.min.js"></script>
    <script src="/website/js/common_scripts.js"></script>
	@yield('scripts')
    <script src="/website/js/main.js"></script>
	<script src="/website/assets/validate.js"></script>

</body>
</html>

resources/views/website/main.blade.php
@extends('website.layout')

@section('content')


<section class="hero_single version_2">
    <div class="wrapper">
        <div class="container">
            <h3>What would you learn?</h3>
            <p>Increase your expertise in business, technology and personal development</p>
            <form>
                <div id="custom-search-input">
                    <div class="input-group">
                        <input type="text" class=" search-query" placeholder="Ex. Architecture, Specialization...">
                        <input type="submit" class="btn_search" value="Search">
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<!-- /hero_single -->

<div class="features clearfix">
    <div class="container">
        <ul>
            <li><i class="pe-7s-study"></i>
                <h4>+200 courses</h4><span>Explore a variety of fresh topics</span>
            </li>
            <li><i class="pe-7s-cup"></i>
                <h4>Expert teachers</h4><span>Find the right instructor for you</span>
            </li>
            <li><i class="pe-7s-target"></i>
                <h4>Focus on target</h4><span>Increase your personal expertise</span>
            </li>
        </ul>
    </div>
</div>
<!-- /features -->

<div class="container-fluid margin_120_0">
    <div class="main_title_2">
        <span><em></em></span>
        <h2>Udema Popular Courses</h2>
        <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
    </div>
    <div id="reccomended" class="owl-carousel owl-theme">
        @foreach ($courses as $course)

        <div class="item">
            <div class="box_grid">
                <figure>
                    <a href="#0" class="wish_bt"></a>
                    <a href="#">
                    <div class="preview"><span>Preview course</span></div><img src="{{asset('website/img/'.$course->image)}}" class="img-fluid" alt=""></a>
                    <div class="price">${{$course->price}}</div>

                </figure>
                <div class="wrapper">
                <small>{{$course->category->name}}</small>
                <a href="{{route('courses.show',$course->id)}}"><h3>{{$course->name}}</h3></a>
                <p>{{$course->short_description}}</p>
                <div class="rating">
@include('website\includes\rate_star',['rate'=>$course->reviews->avg('rate')] )
                <small>({{$course->reviews->count()}})</small>
            </div>
                </div>
                <ul>
                    <li><i class="icon_clock_alt"></i>&nbsp;{{$course->lessons->sum('duration')}}
                    min</li>
                    {{-- <li><i class="icon_like"></i> 890</li> --}}
                    <li><a href="{{route('courses.show', $course->id)}}">Enroll now</a></li>
                </ul>
            </div>
        </div>
        @endforeach
        <!-- /item -->

    </div>
    <!-- /carousel -->
    <div class="container">
        <p class="btn_home_align"><a href="{{route('courses.index')}}" class="btn_1 rounded">View all courses</a></p>
    </div>
    <!-- /container -->
    <hr>
</div>
<!-- /container -->

<div class="container margin_30_95">
    <div class="main_title_2">
        <span><em></em></span>
        <h2>Udema Categories Courses</h2>
        <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
    </div>
    <div class="row">
        @foreach ($categories as $category)

<div class="col-lg-4 col-md-6 wow" data-wow-offset="150">
<a href="#0" class="grid_item">
    <figure class="block-reveal">
    <div class="block-horizzontal"></div>
    <img src="{{asset('website/img/'.$category->image)}}" class="img-fluid" alt="" style="width: 350px; height: 187px">
  <div class="info">
  <small><i class="ti-layers"></i>{{$category->courses->count()}} Programmes</small>
         <h3>{{$category->name}}</h3>
            </div>
        </figure>
    </a>
</div>
        <!-- /grid_item -->
        @endforeach
    </div>
    <!-- /row -->
</div>
<!-- /container -->

<div class="bg_color_1">
    <div class="container margin_120_95">
        <div class="main_title_2">
            <span><em></em></span>
            <h2>News and Events</h2>
            <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
        </div>
        <div class="row">
            @foreach ($posts as $post)

            <div class="col-lg-6">
            <a class="box_news" href="{{route('posts.show', $post->id)}}">
                <figure><img src="{{asset('website/img/'.$post->image)}}" alt="">
                <figcaption><strong>{{\Carbon\Carbon::parse($post->created_at)->format('d')}}</strong>{{\Carbon\Carbon::parse($post->created_at)->format('M')}}</figcaption>
                </figure>
                <ul>
                        {{-- <li>Mark Twain</li> --}}
                    <li>{{\Carbon\Carbon::parse($post->created_at)->format('d / m / Y')}}</li>
                    </ul>
                <h4>{{$post->name}}</h4>
                <p>{{Str::limit($post->description, 110)}}</p>
                </a>
            </div>
            <!-- /box_news -->
            @endforeach
        </div>
        <!-- /row -->
        <p class="btn_home_align"><a href="{{route('posts.index')}}" class="btn_1 rounded">View all news</a></p>
    </div>
    <!-- /container -->
</div>
<!-- /bg_color_1 -->

<div class="call_section">
    <div class="container clearfix">
        <div class="col-lg-5 col-md-6 float-right wow" data-wow-offset="250">
            <div class="block-reveal">
                <div class="block-vertical"></div>
                <div class="box_1">
                    <h3>Enjoy a great students community</h3>
                    <p>Ius cu tamquam persequeris, eu veniam apeirian platonem qui, id aliquip voluptatibus pri. Ei mea primis ornatus disputationi. Menandri erroribus cu per, duo solet congue ut. </p>
                    <a href="#0" class="btn_1 rounded">Read more</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/call_section-->


@endsection

resources/views/website/nav.blade.php
<nav id="menu" class="main-menu">
    <ul>
        <li><span><a href="{{route('main')}}">Home</a></span>
        </li>
        <li><span><a href="{{route('courses.index')}}">Courses</a></span>
        </li>
        <li><span><a href="{{route('posts.index')}}">Blog</a></span>
        </li>
        <li><span><a href="{{route('about')}}">About</a></span>
        </li>
        <li><span><a href="{{route('contact')}}">Contact Us</a></span>
        </li>


    </ul>
</nav>