routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SiteController@index')->name('main');
Route::get('about','SiteController@about')->name('about');
Route::get('contact','SiteController@contact')->name('contact');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courses', 'Website\CourseController');
Route::resource('posts', 'Website\PostController');
Route::get('courses_enroll/{course_id}','Website\CourseController@enroll')->name('course.enroll');

Route::group(['prefix' => 'dashboard','as'=>'dashboard.','middleware'=>'admin','namespace'=>'Dashboard'], function () {

Route::get('/', 'MainController@index')->name('home');
// user routes controllers
Route::resource('users', 'UserController');
Route::get('delete_user/{id}','UserController@destroy')->name('users.user_destroy');

// category routes controllers
Route::resource('categories', 'CategoryController');
Route::get('delete_category/{id}','CategoryController@destroy')->name('categories.category_destroy');

// courses routes controllers
Route::resource('courses', 'CourseController');
Route::get('delete_course/{id}','CourseController@destroy')->name('courses.course_destroy');

// lessons routes controllers
Route::resource('lessons', 'LessonController');
Route::get('delete_lesson/{id}','LessonController@destroy')->name('lessons.lesson_destroy');

// messages routes controllers
Route::resource('message', 'ContactController');
Route::get('delete_message/{id}','ContactController@destroy')->name('message.message_destroy');

});

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $categories = Category::orderBy('id', 'desc')->get();
          return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'required|file|max:2048|mimes:png,jpeg,jpg',
        ]);

        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Category::create($inputes);
        return redirect(route('dashboard.categories.index'))->with('success', 'You Have Added New Category Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);
        return view('dashboard.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'required|file|max:2048',
        ]);
        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Category::find($id)->update($inputes);
        return redirect(route('dashboard.categories.index'))->with('success', 'You Have Updated This Category Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if(!$category)  return back()->with('error','Category Does Not Exist!');
        $category->delete();
        return redirect(route('dashboard.categories.index'))->with('success', 'Category Deleted Successfully.');
    }
}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Contact;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $messages = Contact::all();
        return view('dashboard.messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'email'=>'required|email|max:191|unique:users,email',
            'phone'=>'required|string|max:191|unique:users,phone',
            'message'=>'required',
        ]);

        // if(!auth()->user()) return back()->with('error', 'You Are Not Registered In Our Website!');
       Contact::create($request->all());
       return redirect(route('contact'))->with('success', 'Your Message Sent Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $message = Contact::findOrFail($id);
        return view('dashboard.messages.show', compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = Contact::find($id);
        if(!$message) return back()->with('error', 'Message Does not Exist!');
        $message->delete();
        return redirect(route('dashboard.messages.index'))->with('success', 'Message Deleted Successfully.');
    }
}

app/Http/Controllers/Dashboard/CourseController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Course;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courses = Course::all();
        return view('dashboard.courses.index', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.courses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'rquired|file|max:2048|mimes:png,jpeg,jpg',
            'short_description'=>'required',
            'long_description'=>'required',
            'price'=>'required|decimal',
            'category_id'=>'required|string|max:191',
        ]);
        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Course::create($inputes);
        return redirect(route('dashboard.courses.index'))->with('success', 'You Have Added New Course Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $course = Course::findOrFail($id);
        return view('dashboard.courses.show', compact('course'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $course = Course::findOrFail($id);
        return view('dashboard.courses.edit', compact('course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $course = Course::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'image'=>'rquired|file|max:2048|mimes:png,jpeg,jpg',
            'short_description'=>'required',
            'long_description'=>'sometimes',
            'price'=>'required|decimal',
            'category_id'=>'required|string|max:191',
        ]);
        $inputes = $request->except(['image']);
        if ($request->hasFile('image')) {
            $inputes['image'] = uploader($request, 'image');
        }
        Course::find($id)->update($inputes);
        return redirect(route('dashboard.courses.index'))->with('success', 'You Have Updated This Course Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $course = Course::find($id);
        if(!$course) return back()->with('error', 'Course Does not Exist!');
        $course->delete();
        return redirect(route('dashboard.courses.index'))->with('success', 'Course Deleted Successfully.');

    }
}

app/Http/Controllers/Dashboard/LessonController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Lesson;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lessons = Lesson::orderBy('course_id', 'asc')->get();
        return view('dashboard.lessons.index', compact('lessons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.lessons.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'url'=>'required|url|unique:lessons,url',
            'duration'=>'required|date',
            'course_id'=>'required|string|max:191',
        ]);

        $inputes = $request->all();
        Lesson::create($inputes);
        return redirect(route('dashboard.lessons.index'))->with('success', 'You Have Added New Lesson Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $lesson = Lesson::findOrFail($id);
        return view('dashboard.lessons.show', compact('lesson'));

        }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lesson = Lesson::findOrFail($id);
        return view('dashboard.lessons.edit', compact('lesson'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'=>'required|string|max:191',
            'url'=>'required|url|unique:lessons,url',
            'duration'=>'required|date',
            'course_id'=>'required|string|max:191',
        ]);

        $inputes = $request->all();
        Lesson::find($id)->update($inputes);
        return redirect(route('dashboard.lessons.index'))->with('success', 'You Have Updated This Lesson Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lesson = Lesson::find($id);
        if(!$lesson) return back()->with('error', 'Lesson Does not Exist!');
        $lesson->delete();
        return redirect(route('dashboard.lessons.index'))->with('success', 'Lesson Deleted Successfully.');
    }
}

app/Http/Controllers/Dashboard/MainController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index()
    {
        return view('Dashboard.main');
    }
}

resources/views/Dashboard/Layouts/categoryform.blade.php
<div class="panel-heading">
        @if (isset($category))
        <h5 class="panel-title">Edit Category: {{$category->name}} </h5>
        @else
        <h5 class="panel-title">Fill this form please: </h5>
        @endif
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>
<div class="panel-body">
    <fieldset class="content-group">
        <div class="form-group">
            <label class="control-label col-lg-2">Category Name: </label>
                <div class="col-lg-10">
                    <div class="input-group">
                    <span class="input-group-addon"><i class="icon-comment"></i></span>
                            {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Type Category Name']) !!}
                </div>
            </div>
        </div>
            <div class="form-group">
                <label class="control-label col-lg-2">Category Picture: </label>
                <div class="col-lg-10">
@if (isset($category))
@if($category->image != null)
<div class="media-left">
   <a href="#"><img src="{{getimage($category->image)}}"
                     style="width: 58px; height: 58px; border-radius: 2px;" alt=""></a>
</div>
@endif
@endif
                    <div class="uploader">
                        {!! Form::file('image', ['class'=>'file-styled','aria-required'=>true]) !!}
                        <span class="filename" style="user-select: none;">No file selected</span><span class="action btn bg-blue" style="user-select: none;">Choose File</span>
                    </div>
                </div>
            </div>
<br><br><br><br>
<div class="form-group">
    <div class="text-left">
        <button type="submit" class="btn bg-teal-400">Save Changes <i class="icon-arrow-right14 position-right"></i></button>
    </div>
</div>
</fieldset>
</div>

resources/views/Dashboard/Layouts/courseform.blade.php
   <div class="panel-heading">
        @if (isset($course))
        <h5 class="panel-title">Edit Course: {{$course->name}} </h5>
        @else
        <h5 class="panel-title">Fill this form please: </h5>
        @endif

        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>
<div class="panel-body">
            <fieldset class="content-group">
                <div class="form-group">
                    <label class="control-label col-lg-2">Course Name: </label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="icon-insert-template"></i></span>
                            {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Type Course Name']) !!}
                        </div>
                    </div>
                </div><br>
                <div class="form-group">
                    <label class="control-label col-lg-2">Category: </label>
                    <div class="col-lg-10">
                     {!! Form::select('category_id', categoryId(), null, ['class'=>'form-control','placeholder'=>'Select Category']) !!}
                </div>
                </div><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Course Picture: </label>
                <div class="col-lg-10">
@if (isset($course))
@if($course->image != null)
<div class="media-left">
   <a href="#"><img src="{{getimg($course->image)}}"
                     style="width: 58px; height: 58px; border-radius: 2px;" alt=""></a>
</div>
@endif
@endif
                    <div class="uploader">
                        {{-- <input type="file" name="styled_file image" class="file-styled" required="required" aria-required="true">--}}
                        {!! Form::file('image', ['class'=>'file-styled','aria-required'=>true]) !!}
                        <span class="filename" style="user-select: none;">No file selected</span><span class="action btn bg-blue" style="user-select: none;">Choose File</span>
                        {{-- <span class="help-block">Extension : gif, png, jpg , jpeg</span> --}}
                    </div>
                </div>
            </div><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Course Price:</label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <span class="input-group-addon">$</span>
                        {!! Form::text('price',null, ['class'=>'form-control', 'placeholder'=>'Type course price']) !!}
                        <span class="input-group-addon">.00</span>
                    </div>
                </div>
            </div><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Short Description</label>
                <div class="col-lg-10">
                    {{ Form::textarea('short_description', null, array('class' =>'form-control', 'cols' => 3, 'rows' =>3, 'placeholder' => 'Type a description here...'))}}
                </div>
            </div><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Full Description</label>
                <div class="col-lg-10">
                    {{ Form::textarea('long_description', null, array('class' =>'form-control', 'cols' => 5, 'rows' =>5, 'placeholder' => 'Type the full description here...'))}}
                </div>
            </div>
<br><br><br><br>
<div class="form-group">
    <div class="text-left">
        <button type="submit" class="btn bg-teal-400">Save Changes <i class="icon-arrow-right14 position-right"></i></button>
    </div>
</div>
</fieldset>
</div>

resources/views/Dashboard/Layouts/form.blade.php
    <div class="panel-heading">
        @if (isset($user))
        <h5 class="panel-title">Edit User: {{$user->name}} </h5>
        @else
        <h5 class="panel-title">Fill this form please: </h5>
        @endif

        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>
<div class="panel-body">

            <fieldset class="content-group">

                <div class="form-group">
                    <label class="control-label col-lg-2">Your Name: </label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="icon-user"></i></span>
                            {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Type Your Name']) !!}
                            {{-- <input type="text" class="form-control" placeholder="Type Your Name" name="name" value="{{isset($user)?$user->name:''}}"> --}}
                        </div>
                    </div>
                </div><br><br>
                <div class="form-group">
                    <label class="control-label col-lg-2">Your E-mail: </label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <span class="input-group-addon">@</span>
                            {{-- <input type="text" class="form-control" placeholder="example@info.com" name="email"> --}}
                        {!! Form::email('email',null,['class'=>'form-control','placeholder'=>'example@info.com']) !!}
                        </div>
                    </div>
                </div><br><br>
                <div class="form-group">
                    <label class="control-label col-lg-2">Phone: </label>
                    <div class="col-lg-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fas fa-mobile-alt"></i></span>
                    {{-- <input type="text" class="form-control" data-mask="(999) 999-9999" placeholder="Enter your phone #" name="phone"> --}}
                    {!! Form::tel('phone',null,['class'=>'form-control','placeholder'=>'Enter your Phone #','data-mask'=>'(999) 999-9999']) !!}
                    </div>
                </div>
                </div><br><br>
                <div class="form-group">
                    <label class="control-label col-lg-2">Your password:</label>
                    <div class="col-lg-10">
                    <div class="input-group">
                    <span class="input-group-addon"><i class="fas fa-key"></i></span>
                    {{-- <input type="password" class="form-control" placeholder="Your strong password" name="password"> --}}
                    {!! Form::password('password',['class'=>'form-control','placeholder'=>'Your strong password']) !!}
                </div>
            </div>
            </div><br><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Repeat Your password:</label>
                <div class="col-lg-10">
                <div class="input-group">
                <span class="input-group-addon"><i class="fas fa-key"></i></span>
                {!! Form::password('password_confirmation',['class'=>'form-control','placeholder'=>'Retype your password']) !!}
            </div>
        </div>
        </div><br><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Your Picture: </label>
                <div class="col-lg-10">
@if (isset($user))
@if($user->image != null)
<div class="media-left">
   <a href="#"><img src="{{getimg($user->image)}}"
                     style="width: 58px; height: 58px; border-radius: 2px;" alt=""></a>
</div>
@endif
@endif
                    <div class="uploader">
                        {{-- <input type="file" name="styled_file image" class="file-styled" required="required" aria-required="true">--}}
                        {!! Form::file('image', ['class'=>'file-styled','aria-required'=>true]) !!}
                        <span class="filename" style="user-select: none;">No file selected</span><span class="action btn bg-blue" style="user-select: none;">Choose File</span>
                        {{-- <span class="help-block">Extension : gif, png, jpg , jpeg</span> --}}
                    </div>
                </div>
            </div><br><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Active Status: </label>
                <div class="col-lg-10">
                 {!! Form::select('is_active', statusArray(), null, ['class'=>'form-control','placeholder'=>'Select User Status']) !!}
                {{-- <select class="selectbox form-control" name="is_active">
                    <option value="1">Active</option>
                    <option value="0">Suspended</option>
                </select> --}}
            </div>
            </div><br><br>
            <div class="form-group">
                <label class="control-label col-lg-2">Access Role: </label>
                <div class="col-lg-10">
                 {!! Form::select('role', userRoles(), null, ['class'=>'form-control', 'placeholder'=>'Select User Role']) !!}
            </div>
            </div>
<br><br>
<div class="form-group">
    <div class="text-left">
        <button type="submit" class="btn bg-teal-400">Save Changes <i class="icon-arrow-right14 position-right"></i></button>
    </div>
</div>
</fieldset>
</div>

resources/views/Dashboard/Layouts/lessonform.blade.php
<div class="panel-heading">
    @if (isset($lesson))
    <h5 class="panel-title">Edit Lesson: {{$lesson->name}} </h5>
    @else
    <h5 class="panel-title">Fill this form please: </h5>
    @endif
    <div class="heading-elements">
        <ul class="icons-list">
            <li><a data-action="collapse"></a></li>
            <li><a data-action="reload"></a></li>
            <li><a data-action="close"></a></li>
        </ul>
    </div>
</div>
<div class="panel-body">
    <fieldset class="content-group">

    <div class="form-group">
        <label class="control-label col-lg-2">Lesson Name: </label>
            <div class="col-lg-10">
                <div class="input-group">
                <span class="input-group-addon"><i class="icon-menu6"></i></span>
                {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Type Lesson Name']) !!}
            </div>
        </div>
    </div><br>
<div class="form-group">
    <label class="control-label col-md-2">URL</label>
    <div class="col-md-10">
        <div class="input-group">
        <span class="input-group-addon"><i class="icon-link"></i></span>
{!! Form::url('url', null, ['class'=>'form-control']) !!}
        </div>
    </div>
</div><br>

<div class="form-group">
    <label class="control-label col-md-2">Time</label>
    <div class="col-md-10">
{!! Form::time('duration', null, ['class'=>'form-control']) !!}
    </div>
</div><br>

<div class="form-group">
    <label class="control-label col-lg-2">Course Lesson: </label>
    <div class="col-lg-10">
{!! Form::select('course_id', courseId(),null, ['class'=>'form-control','placeholder'=>'Select Course Lesson']) !!}
    </div>
</div>
<br><br><br><br>
<div class="form-group">
<div class="text-left">
    <button type="submit" class="btn bg-teal-400">Save Changes <i class="icon-arrow-right14 position-right"></i></button>
</div>
</div>
</fieldset>
</div>

resources/views/Dashboard/Layouts/nav.blade.php
<!-- Main -->
<li class="navigation-header"><span>Main</span> <i class="icon-menu" title="Main pages"></i></li>
<li class="active"><a href="{{route('dashboard.home')}}"><i class="icon-home4"></i> <span>Home</span></a></li>
<li>
    <a href="#"><i class="icon-users4"></i> <span>Users</span></a>
    <ul>
        <li><a href="{{route('dashboard.users.index')}}"><i class="fa fa-users"></i>All Users</a></li>
        <li><a href="{{route('dashboard.users.create')}}"><i class="fa fa-user-plus"></i>Add New User</a></li>
    </ul>
</li>

<li>
    <a href="#"><i class="fas fa-archive"></i><span>Categories</span></a>
    <ul>
        <li><a href="{{route('dashboard.categories.index')}}"><i class="fas fa-clone"></i>All Categories</a></li>
        <li><a href="{{route('dashboard.categories.create')}}"><i class="fas fa-plus-square"></i></i>Add New Category</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fas fa-chalkboard-teacher"></i><span>Courses</span></a>
    <ul>
        <li><a href="{{route('dashboard.courses.index')}}"><i class="fas fa-laptop-code"></i>All Courses</a></li>
        <li><a href="{{route('dashboard.courses.create')}}"><i class="fas fa-book-reader"></i>Add New Course</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="far fa-clipboard"></i><span>Lessons</span></a>
    <ul>

        <li><a href="{{route('dashboard.lessons.index')}}"><i class="fas fa-copy"></i></i>All Lessons</a></li>
        <li><a href="{{route('dashboard.lessons.create')}}"><i class="fas fa-file"></i>Add New Lesson</a></li>
    </ul>
</li>
{{-- ================================================================== --}}

<li><a href="#"><i class="fas fa-envelope"></i><span>Messages</span></a>
    <ul>
        <li><a href="{{route('dashboard.message.index')}}"><i class="fas fa-envelope-open-text"></i></i>All Messages</a></li>
    </ul>
</li>

<li><a href="{{route('logout')}}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
    <i class="fa fa-sign-out-alt"></i><span> Logout</span>
</a>
</li>
<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
</form>